/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApiManagerRouteImport } from './routes/api-manager'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as MessagingRouteImport } from './routes/messaging'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WebhooksRouteImport } from './routes/webhooks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManagerRoute = ApiManagerRouteImport.update({
  id: '/api-manager',
  path: '/api-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagingRoute = MessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/api-manager': typeof ApiManagerRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/logs': typeof LogsRoute
  '/messaging': typeof MessagingRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/webhooks': typeof WebhooksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/api-manager': typeof ApiManagerRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/logs': typeof LogsRoute
  '/messaging': typeof MessagingRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/webhooks': typeof WebhooksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/api-manager': typeof ApiManagerRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/logs': typeof LogsRoute
  '/messaging': typeof MessagingRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/webhooks': typeof WebhooksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/api-manager'
    | '/docs'
    | '/help'
    | '/history'
    | '/logs'
    | '/messaging'
    | '/sessions'
    | '/settings'
    | '/webhooks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/api-manager'
    | '/docs'
    | '/help'
    | '/history'
    | '/logs'
    | '/messaging'
    | '/sessions'
    | '/settings'
    | '/webhooks'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/api-manager'
    | '/docs'
    | '/help'
    | '/history'
    | '/logs'
    | '/messaging'
    | '/sessions'
    | '/settings'
    | '/webhooks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApiManagerRoute: typeof ApiManagerRoute
  DocsRoute: typeof DocsRoute
  HelpRoute: typeof HelpRoute
  HistoryRoute: typeof HistoryRoute
  LogsRoute: typeof LogsRoute
  MessagingRoute: typeof MessagingRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  WebhooksRoute: typeof WebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-manager': {
      id: '/api-manager'
      path: '/api-manager'
      fullPath: '/api-manager'
      preLoaderRoute: typeof ApiManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaging': {
      id: '/messaging'
      path: '/messaging'
      fullPath: '/messaging'
      preLoaderRoute: typeof MessagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApiManagerRoute: ApiManagerRoute,
  DocsRoute: DocsRoute,
  HelpRoute: HelpRoute,
  HistoryRoute: HistoryRoute,
  LogsRoute: LogsRoute,
  MessagingRoute: MessagingRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  WebhooksRoute: WebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
